### ISSUE TITLE
Real Visitor IP address isn't passed to the container

### ISSUE THREAD

**Issue by demianrihs** [bitnami/bitnami-docker-prestashop#100]
**Description**

I deployed the container and I am using a nginx reverse proxy on my server to redirect the domain name to the custom docker port where I am running prestashop. Unfortunately prestashop doesn't see the IP address from the client, only the internal docker network gateway is recognized.

**Steps to reproduce the issue:**

1. Deploy bitnami/prestashop on a production enviroment
2. Setup NGINX proxy to redirect a domain URL to the port of the docker container
3. Enable maintenance mode and whitelist "your" IP (the system fills the gateway address of the docker network)

**Describe the results you received:**

I want to restric the catalogue visit by specific countries. Since the IP of the visitors are not passed to the store everyone is getting filtered out

**Describe the results you expected:**

Prestashop to recognize the IP address of the visitors

**Additional information you deem important (e.g. issue happens only occasionally):**

I am wondering if this issue described here might be the cause?

https://github.com/nginx-proxy/nginx-proxy/issues/130

**Comment by miguelaeh** [comment]
Hi @demianrihs 
It seems this is not an issue with the image but with your infrastructure.
I guess you are getting the IP of the reverse proxy? Probably it is not properly configured
