### ISSUE TITLE
stuck at Trying to connect to the database server 

### ISSUE THREAD

**Issue by C-Fu** [bitnami/bitnami-docker-prestashop#105]
What am I doing wrong? I just modified the included docker-compose.yml and edited a bit, but it can't seem to find the database container.

```version: '2'
services:
  presta-mariadb:
    container_name: presta-mariadb
    image: docker.io/bitnami/mariadb:10.3
    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
      - MARIADB_ROOT_PASSWORD=somepass
      - MARIADB_PASSWORD=somepass
    volumes:
      - ./db:/bitnami/mariadb
  prestashop:
    container_name: prestashop
    image: docker.io/bitnami/prestashop:latest
    ports:
      - '880:8080'
      - '8443:8443'
    environment:
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_HOST=presta-mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - PRESTASHOP_PASSWORD=somepass
      - PRESTASHOP_DATABASE_PASSWORD=somepass
      - PRESTASHOP_COUNTRY=my
#      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data:/bitnami/prestashop
    depends_on:
      - presta-mariadb
networks:
  default:
    name: app_net
```

first it says can't create /bitnami/mariadb/data as the access is denied. Fine, I'll just mkdir ./db/data.
Then it says
presta-mariadb    | mariadb 16:22:24.63 INFO  ==> Setting user option
presta-mariadb    | mariadb 16:22:24.64 INFO  ==> Installing database
and
prestashop        | prestashop 16:22:25.49 INFO  ==> Trying to connect to the database server
prestashop        | prestashop 16:23:25.95 ERROR ==> Could not connect to the database

and gets stuck there after 15 mins. It's on an nvme drive, so can't be that long. Also, shouldn't the main description at the main page change to use MARIADB_* env instead of MYSQL_* since the included docker-compose.yml uses MARIADB now?

Cheers and thanks for reading!

**Comment by migruiz4** [comment]
Hi @C-Fu,

I'd say it is not a problem with your `docker-compose` as I haven't been able to reproduce your issue using a copy of it.

It is probably caused by a permission issue with the folders `./db` and `./data` having the wrong ownership.

The prestashop and mariadb container run as user `1001`, so setting ownership of both `./db` and `./data`as it follows may fix the issue:
```bash
chown 1001:root ./db ./data
```

**Comment by C-Fu** [comment]
Thanks @migruiz4 ! Is there a way to set the PID and GUID via environment variables, similar to linuxserver's containers?

**Comment by migruiz4** [comment]
Indeed there is a way to set the UID and GUID via environment variables.

You can do it by adding `user: "${UID}:${GID}"` to your docker compose:

```yaml  presta-mariadb:
services:
  presta-mariadb:
    container_name: presta-mariadb
    image: docker.io/bitnami/mariadb:10.3
    user: "${UID}:${GID}"
    ...
  prestashop:
    container_name: prestashop
    image: docker.io/bitnami/prestashop:latest
    user: "${UID}:${GID}"
    ...
```
Then run:
```
UID=${UID} GID=${GID} docker-compose up
```

That would configure the container to run with the same `user:group` you are using to run docker-compose, but you can replace them with your custom environment variables if needed.

I hope that is what you are looking for. Let me know if that works for you.
