### ISSUE TITLE
Configure client certificate for database 

### ISSUE THREAD

**Issue by BartoszCoyote** [bitnami/bitnami-docker-prestashop#108]
Hello, 
I need to configure client certificate for database.

I see bitnami magento have whole section for Database server connection, and i just need to pass path to cert file 
https://github.com/bitnami/bitnami-docker-magento#database-server-connection-credentials-and-configuration

but I can't see similar options for presta.

**Comment by pablogalegoc** [comment]
Hi @BartoszCoyote! Is this actually supported in Prestashop? I couldn't find anything on their documentation, only this unresolved support case on their forums: [Use SSL on Mysql Setup](https://www.prestashop.com/forums/topic/1015202-use-ssl-on-mysql-setup/). Could you point where I can find more information?

**Comment by BartoszCoyote** [comment]
Which means all the stores using PrestaShop connect to databases in an unencrypted and unsecured way? @pablogalegoc

**Comment by pablogalegoc** [comment]
As you pointed out, the PrestaShop container currently doesn't support SSL configuration for the database, feel free to contribute with this functionality via a PR. We'd be glad to review and help with the release!
