### ISSUE TITLE
Administration link redirect to port 8080 on localhost

### ISSUE THREAD

**Issue by zorrobiwan** [bitnami/bitnami-docker-prestashop#112]
**Description**

**Steps to reproduce the issue:**

1. Download image using the curl command (curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-prestashop/master/docker-compose.yml > docker-compose.yml)
2. Launch containers (docker-compose up -d)
3. Visit http://localhost/administration

**Describe the results you received:**

Web server answers 301 and redirect to http://localhost:8080/administration which is not open

**Describe the results you expected:**

To stay on port 80

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 7
  Running: 2
  Paused: 0
  Stopped: 5
 Images: 40
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.807GiB
 Name: docker-desktop
 ID: BVO4:645F:QSVH:BWPK:HL5H:AO3T:PC76:PQQU:TBU6:YI75:ETN2:5QEP
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

I'm on docker for MAC
![image](https://user-images.githubusercontent.com/2226019/125429053-8dd248e8-1df5-406b-ae5f-8fba86673733.png)

**Comment by marcosbc** [comment]
@zorrobiwan If you access it via `/administration/` (instead of `/administration`) it should work.

Unfortunately this is a limitation of the Apache web server's `mod_dir` module. What happens is that when you access a folder at `/foldername` and that folder exists, it tries to redirect you to `/foldername/`. However it is performing an absolute redirection and is unable to determine the hostname that was being used to access the server (due to the Docker proxy), so it redirects to the wrong address.

In any case, are you clicking a specific link in the PrestaShop UI, or is it that you are just accessing it through `/administration` in the browser URL bar?

**Comment by zorrobiwan** [comment]
Hi @marcosbc thanks for your quick reply.
You're right it's working.
Sorry for boring you about such a stupid problem. I should have tested it.
Anyway, could be great to add this in the README.md :)
My $0.02

Thanks again
