### ISSUE TITLE
rm: cannot remove '/opt/bitnami/prestashop': Permission denied

### ISSUE THREAD

**Issue by qcmr** [bitnami/bitnami-docker-prestashop#114]
Hello,

I am facing a blocking issue with this Prestashop image. See description below.
Thanks for your help.

Regards,
Q

**Description**

**Steps to reproduce the issue:**

1. rebuild the prestashop image after updating the "USER 1000" instead of "USER 1001" in the Dockerfile (to match my own user uid)
2. update the docker-compose file to mount host directories as data volumes
3. spin-up the container

**Describe the results you received:**

```
prestashop-1  | prestashop 06:44:38.11 INFO  ==> Running install script
prestashop-1  | prestashop 06:45:28.02 INFO  ==> Updating store settings
prestashop-1  | prestashop 06:45:28.07 INFO  ==> Persisting PrestaShop installation
prestashop-1  | rm: cannot remove '/opt/bitnami/prestashop': Permission denied
prestashop-1 exited with code 1

```

**Describe the results you expected:**

it should work

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Version**

```
Client:
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.17.3
 Git commit:        dea9396e18
 Built:             Sat Nov 20 12:57:52 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.3
  Git commit:       847da184ad
  Built:            Sat Nov 20 12:57:08 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.5.8
  GitCommit:        1e5ef943eb76627a6d3b6de8cd1ef6537f393a71.m
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., 2.2.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 38
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1e5ef943eb76627a6d3b6de8cd1ef6537f393a71.m
 runc version: v1.0.2-0-g52b36a2d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.5-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.32GiB
 Name: pegase
 ID: YAVW:W2HE:ZXV2:SCRP:FR7H:WANB:AZC4:JCFO:3PHP:BJEG:Y5V5:F5JA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
Docker Compose version 2.2.0
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

N/A

**Comment by carrodher** [comment]
The approach used to convert root containers into non-root is to use a random user that is part of the root group, probably your user 1000 is not part of the root group as 1001 is, can you check that?

You can find more info in the following doc sites:
- https://engineering.bitnami.com/articles/why-non-root-containers-are-important-for-security.html
- https://docs.bitnami.com/tutorials/work-with-non-root-containers/

**Comment by qcmr** [comment]
On the host side the user 1000 is indeed not part of the root group and there is no reason for it to be as it is a user.

It is a tricky situation: 
- 1001 user does not exist on the host
- the data volumes are in a place owned by 1000 (/home) to be able to access them (even though I could sudo, the same way I use it with the docker commands.

So, what should be the setup? Create a 1001 user on the host and put it in the root group? I do not understand the logic: being part of the root group (0) does not grant any privilege so maybe the error will be solved but the data volumes won't be writable.

**Comment by javsalgar** [comment]
Hi,

In order to make the container work in environments like Openshift, any random user that runs the container must belong to the `root` group. If you do not want the 1000 user to belong to the `root` group, I advise you to check the permissions of the volumes you are mounting in the container, could you try running `ls -la` in these folders to check the permissions?
