### ISSUE TITLE
ARM version

### ISSUE THREAD

**Issue by PPCM** [bitnami/bitnami-docker-prestashop#116]
### Name and Version

bitnami-docker-prestashop all versions

### What is the problem this feature will solve?

The docker image is not available for ARM processor

### What is the feature you are proposing to solve the problem?

Please, can you compile the docker image for ARM processor

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
