### ISSUE TITLE
Needs linux/arm build version on Docker Hub

### ISSUE THREAD

**Issue by okitoxo** [bitnami/bitnami-docker-prestashop#118]
### Name and Version

bitnami/prestashop

### What is the problem this feature will solve?

On Apple Silicon chips (M1) we can't use these images builded only for amd64

### What is the feature you are proposing to solve the problem?

Publish version linux/arm on Docker Hub building with docker buildx

**Comment by juan131** [comment]
Duplicate of https://github.com/bitnami/charts/issues/7305
