### ISSUE TITLE
Prestashop 1.7 docker-compose file

### ISSUE THREAD

**Issue by babyfooter** [bitnami/bitnami-docker-prestashop#43]
Hi guys,

Is there a way to use docker-compose in order to use Prestashop 1.7 version?

Thx in advance!

**Comment by prydonius** [comment]
Hey @babyfooter,

Looks like 1.7 was released a couple of days ago, and you can get that version by pulling the latest tag, or fixing the image to `bitnami/prestashop:1.7.0.4-r0` in your Compose file.

**Comment by juan131** [comment]
@babyfooter did you try using bitnami/prestashop:1.7.0.4-r0 as @prydonius suggested? Is that what you were looking for?

**Comment by babyfooter** [comment]
Hi @juan131 , that's fine with bitnami/prestashop:1.7.0.4-r0, thank you.

Have a good day!

**Comment by juan131** [comment]
Hello @babyfooter can I suggest you to open a different issue in order to discuss how to increase performance? We should stick to the point on every issue.
