### ISSUE TITLE
Can't access Prestashop

### ISSUE THREAD

**Issue by prydonius** [bitnami/bitnami-docker-prestashop#5]
After curl'ing the docker-compose file and running `up`, I see everything starts correctly, but I cannot access Prestashop on port 80.

```
curl localhost -vv
* Rebuilt URL to: localhost/
*   Trying ::1...
* connect to ::1 port 80 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.43.0
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 302 Found
< Date: Thu, 01 Sep 2016 23:42:45 GMT
< Server: Apache/2.4.20 (Unix) OpenSSL/1.0.1t PHP/5.6.21
< X-Powered-By: PHP/5.6.21
< Location: http://172.19.0.3/
< Content-Length: 0
< Connection: close
< Content-Type: text/html; charset=utf-8
<
* Closing connection 0
```

Looks like it's redirecting me to the containers' internal IP? I'm using Docker for Mac.

**Comment by migmartri** [comment]
We should probably list PRESTASHOP_HOST in the docker-compose file.

**Comment by sameersbn** [comment]
@migmartri same goes for the magento chart .

**Comment by sameersbn** [comment]
@prydonius @migmartri p.s. I've added the parameter to the docker-compose.yml file in https://github.com/bitnami/bitnami-docker-prestashop/pull/6/files#diff-4e5e90c6228fd48698d074241c2ba760R18
