### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by babyfooter** [bitnami/bitnami-docker-prestashop#57]
Hi @juan131 @prydonius , bitnami/prestashop:1.7.0.4-r0 is now up and working, thank you. I have a question, my bitnami wordpress and prestashop docker envs are really slow, take so much time to access websites. 

Do you have an idea about how to optimize it using your docker-compose file? 

My configuration is concerning 
> NGinx proxy in front of all dockers
> Memcached mounted in each docker containers
> Standard installation (Apache + Php + MariaDb) from Birnami for each Wordpress and Prestashop containers

For comparaison, it worked fine with a standard Apache installation without Docker.

Have a good day!

**Comment by juan131** [comment]
@babyfooter do you mean that once your Prestashop is up and running the navigation is very slow or do you mean that it takes to long in order to be ready when you `docker-compose up`?

**Comment by babyfooter** [comment]
I mean Prestashop is up and running the navigation is very slow yes

**Comment by davidbhlm-github** [comment]
Hi @babyfooter , this could be an issue with your Docker setup. For example, if your Docker host is different to your host OS (for non-linux OS), and you're mounting volumes, disk performance can suffer.

If you are comparing MySQL on the same host as your Docker host, there may be other things you could look into, such as different mysql options. Also, your nginx and mysql logs could provide you with more info.

I hope it helps.

**Comment by babyfooter** [comment]
Hi. @davidbhlm-github, thx for your feedback.

My docker and OS hosts are the same, host is based on a classic ubuntu OS. 

About docker image conf, thats why I was asking for help, I did not update any custom conf on Bitnami image, is anyone having same low perfs on a bitnami prestashop image?

**Comment by davidbhlm-github** [comment]
Hi @babyfooter ,

Maybe the issue is in the Nginx configuration. Could you check your Nginx logs? Also, could you check if the container has a good performance without Nginx proxy in front of it?

Regards.

**Comment by babyfooter** [comment]
hi @davidbhlm-github,

Sorry for late reply, but was very busy. I just tried this morning to reinstall a clean OVH server + docker + your prestashop image (default docker-compose file).

Seems I have the same performance issue, pages are really slow on browser. I'll have a try with official prestashop image, but if you have some feedback on it, was happy to use Bitnami stuff.

Thx!

**Comment by jotamartos** [comment]
Hi @babyfooter,

We've just tried to reproduce the issue but the latest version of the Bitnami Prestashop container worked fine for us. We accessed some sites in the application along with the administration site and we didn't find any performance issue when testing it. Could you please let us know if the issue happens only when opening the administration site for example or does it happen all the time? 

Regarding the server you are using, could you please let us know the specification of it? 

We would also like to know the results of your site when running this test, if your site is publicly available, could you please use this tool?

https://www.webpagetest.org/

Regards,
Jota

**Comment by babyfooter** [comment]
hi @jotamartos, 

Here are the specifications of the server
OS
Ubuntu Server 16.04 "Xenial Xerus" LTS (64bits)
Boot
Boot from hard drive (no netboot)
Specifications
Serveur - 4Go RAM - Processor D425 - Hard drive 1x1 To

Here is the report you asked. Note that all admin pages are really super long to display.

[sagoeparts.com.170914_MC_2a25e5c8ad1e773b19844263e96782df.har.json.zip](https://github.com/bitnami/bitnami-docker-prestashop/files/1303308/sagoeparts.com.170914_MC_2a25e5c8ad1e773b19844263e96782df.har.json.zip)

**Comment by babyfooter** [comment]
Hi @jotamartos, guys,

I think my issue concerning performance on backoffice is due to Prestashop stuff. I'll check over the web if I could deactivate some module or else...

Thanks for your help.
