### ISSUE TITLE
Where is prestashop files?

### ISSUE THREAD

**Issue by Khangeldy** [bitnami/bitnami-docker-prestashop#62]
I cloned this repo and run docker-compose up. The site is opened in localhost. But i don't know where is the files of prestashop?  Are they mounted on my computer? How can i open they with atom ide?

**Comment by Khangeldy** [comment]
I have arch linux. In there i don't find any folder in /opt .

**Comment by juan131** [comment]
Hello @Khangeldy 

Once you run `docker-compose up`, you can check the container ID where PrestaShop is running by running `docker ps`. Once you have the ID, you can run:

```
docker exec -it CONTAINER-ID bash
```

That will open a bash terminal on the container and, using it, you can fin PrestaShop files at `/opt/bitnami/prestashop/`.

**Comment by Khangeldy** [comment]
@juan131 Thank you.  Next days i will learn docker.
