### ISSUE TITLE
Installing Prestashop with reverse-proxy

### ISSUE THREAD

**Issue by aleksander351** [bitnami/bitnami-docker-prestashop#65]
I want to setup Prestashop with a proxy on a separate network .

I am using nginx-proxy and a docker network, which is not the default one.

Has anybody tried that?

My attempt:

`    environment:

      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=xxx
      - PRESTASHOP_DATABASE_NAME=xxx
      - ALLOW_EMPTY_PASSWORD=yes
      - VIRTUAL_HOST=my-domain.net 
      - LETSENCRYPT_HOST=my-domain.net
      - LETSENCRYPT_EMAIL=my-name@gmail.com`

**Comment by juan131** [comment]
Hi @aleksander351 

It's not very clear to me what container are you using those env. variables on. Could you please share with us the whole `docker-compose.yaml` file you're using?

**Comment by andresbono** [comment]
Thanks for the tips @LatinSuD!!

**Comment by aleksander351** [comment]
My working example.

`

        version: '3'
        services:
          mariadb:
            image: mariadb
            restart: unless-stopped
            environment:
              - MYSQL_ROOT_PASSWORD=xxxxxxxx
              - MYSQL_DATABASE=somedatabase
              - MYSQL_USER=someuser
              - MYSQL_PASSWORD=xxxxxxxx

            volumes:
              - /var/lib/docker/volumes/domain-com-mysql:/var/lib/mysql
            container_name: domain_com_mysql

          prestashop:
            image: prestashop/prestashop
            restart: unless-stopped
            ports:
              - "80XX:80" # some port
            depends_on:
              - mariadb
            environment:
              - DB_SERVER=mysql
              - DB_USER=someuser
              - DB_PASSWD=xxxxxxxx
              - DB_PREFIX=ps_
              - DB_NAME=somedatabase
              - ADMIN_MAIL=someemail@gmail.com
              - ADMIN_PASSWD=xxxxxx
              - PS_DOMAIN=domain.com
              - VIRTUAL_HOST=www.domain.com,domain.com # replace with real domain
              - LETSENCRYPT_HOST=www.domain.com,domain.com # replace with real domain
              - LETSENCRYPT_EMAIL=someemail@gmail.com # replace with real email
            volumes:
              - /var/lib/docker/volumes/domain-com-presta:/var/www/html
            links:
              - mariadb
            container_name: domain_com_prestashop

        volumes:
          domain-com-mysql:
            driver: local
          domain-com-presta:
            driver: local

        networks:
          default:
            external:
              name: somenetwork

`

**Comment by juan131** [comment]
> What I need to do though, at the first Prestashop installation, find the correct IP of the mariadb running container and set it to connect to the database.

Why don't you use the hostname `mariadb`? Docker can resolve the IPs of those pods which services are defined in the `docker-compose.yaml`

**Comment by aleksander351** [comment]
will try that, thanks!

**Comment by juan131** [comment]
Great! Please do not hesitate to let us know if are still running into issues to connect to the database.

**Comment by aleksander351** [comment]
Hi, I could not find any example how to set the hostname to mariadb.

Do you mean, I need to add:

    `
        hostname:
            - mariadb
    `

...to the prestashop container?

**Comment by aleksander351** [comment]
So, if I understand correctly, I should set:

`  - MARIADB_HOST=domain_com_mysql #my mariadb container name`

**Comment by juan131** [comment]
Hi @aleksander351 

You should use the name of the service defined in your **docker-compose.yaml** for MariaDB.

**Comment by garri-dev** [comment]
Hi @aleksander351, 

Could you start Prestashop behind a nginx-proxy with letsenncrypt? 

Pls I need your help!

**Comment by andresbono** [comment]
Hi @garri-dev, you have some tips here: https://github.com/bitnami/bitnami-docker-prestashop/issues/65#issuecomment-449928073.

Let us know if it's useful for your case.

**Comment by garri-dev** [comment]
> Hi @garri-dev, you have some tips here: [#65 (comment)](https://github.com/bitnami/bitnami-docker-prestashop/issues/65#issuecomment-449928073).
> 
> Let us know if it's useful for your case.

No, it's not. I trying to start this service behind this nginx-proxy: https://github.com/dmp1ce/nginx-proxy-letsencrypt

**Comment by andresbono** [comment]
What is the issue that you are facing? If it is related to the Bitnami containers, we can try to help you.

The Bitnami Prestashop container should be ready to work with an nginx proxy and TLS certificates as we maintain a Helm Chart compatible with nginx-ingress-controller. Maybe this note on SSL configuration is helpful for you: https://github.com/bitnami/charts/tree/master/bitnami/prestashop#ssl

**Comment by garri-dev** [comment]
I solve it!

Setting the non-https domain within environment varibles and then updating DB:

`use prestashop
SELECT NAME, VALUE FROM ps_configuration WHERE NAME IN ('PS_SSL_ENABLED', 'PS_SSL_ENABLED_EVERYWHERE');
UPDATE ps_configuration SET VALUE = '1' WHERE NAME IN ('PS_SSL_ENABLED', 'PS_SSL_ENABLED_EVERYWHERE');
SELECT NAME, VALUE FROM ps_configuration WHERE NAME IN ('PS_SSL_ENABLED', 'PS_SSL_ENABLED_EVERYWHERE');`

I hope it helps other!

**Comment by andresbono** [comment]
That's great, @garri-dev!! 🎉 Thanks for sharing your solution.
