### ISSUE TITLE
Must run as root user

### ISSUE THREAD

**Issue by boboldehampsink** [bitnami/bitnami-docker-prestashop#67]
See https://github.com/bitnami/bitnami-docker-wordpress/issues/126#issuecomment-402631235

**Comment by marcosbc** [comment]
Hi @boboldehampsink, we've finally implemented this feature in the tag [1.7.6-8-debian-10-r1](https://github.com/bitnami/bitnami-docker-prestashop#176-8-debian-10-r1) of the container, so I'm proceeding to close this issue.
