### ISSUE TITLE
Can't change administrator password

### ISSUE THREAD

**Issue by LatinSuD** [bitnami/bitnami-docker-prestashop#69]
I get an error when trying to chang administrator password.

1. I log in as administrator
2. Click on "your profile" on the right top corner, then Change Password
3. I introduce current password (bitnami) as well as the new password

I get this error:

Your current password is invalid.

**Version**

- Output of `docker version`:

18.09.0

- Output of `docker-compose version` (if applicable):

1.23.1

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Running in Ubuntu 18.

**Comment by andresbono** [comment]
Hi @LatinSuD, we can reproduce the issue. We will investigate it and we will get back to you.

**Comment by javsalgar** [comment]
Hi,

We found the cause of the issue. We were using `bitnami` as the default password, which is not accepted by Prestashop. We are changing the container to use `bitnami1` as default password.

As you can see in this case, it works without issues

![image](https://user-images.githubusercontent.com/1133777/53748457-a9c07880-3ea5-11e9-82f9-be466930287a.png)

A new version of the container is on the way. In the meantime you can set the `PRESTASHOP_PASSWORD` to a different password (must have 8 letters or more)

**Comment by javsalgar** [comment]
It is now out 

https://github.com/bitnami/bitnami-docker-prestashop/commit/8f3f88c57ab719cf9640858f68ede86e17002c39

If you find any issues with the password, do not hesitate to reopen the ticket
