### ISSUE TITLE
Can't login to prestashop

### ISSUE THREAD

**Issue by sameersbn** [bitnami/bitnami-docker-prestashop#7]
After deploying prestashop, I wasn't able to authenticate myself using the default credentials. I also tried specifying a custom password, which didn't work either.

![ss](https://cloud.githubusercontent.com/assets/410147/18242530/6f0a6eca-7374-11e6-941d-806b008f3576.png)

**Comment by joseajp** [comment]
@sameersbn I have tested the log in process and it works properly. Note that you are trying to authenticate with the administrator account in the frontend shop.
If you go to `CONTAINER-IP/administration` you will find the administrator log in screen and introducing the default credentials you can access to the admin pannel without problems.

**Comment by sameersbn** [comment]
Thanks for the information @joseajp. Will add this information to the README
