### ISSUE TITLE
Set language and country 

### ISSUE THREAD

**Issue by Nittarab** [bitnami/bitnami-docker-prestashop#70]
**Description**

I need to install prestashop in a diffrent language by default, 
In the official [prestashop docker image](https://github.com/PrestaShop/docker/) you can define 2 env variable:
PS_LANGUAGE  
PS_COUNTRY
Can we do the same?

**Comment by andresbono** [comment]
Hi @Nittarab, those environment variables are not supported right now but we can try to add support for multi-language installation in future releases of the container.

We'll keep you updated about this new feature!

**Comment by Nittarab** [comment]
@andresbono I try to inspect the main.js 

```
php.execute(
      'install/index_cli.php',
      [
        `--db_user=${databaseHandler.connection.user}`,
        `--db_password=${databaseHandler.connection.password}`,
        `--db_server=${databaseHandler.connection.host}:${databaseHandler.connection.port}`,
        `--db_name=${databaseHandler.connection.name}`,
        `--domain=${domains.httpDomain}`,
        `--firstname=${$app.firstName}`,
        `--lastname=${$app.lastName}`,
        `--password=${$app.password}`,
        `--email=${$app.email}`,
        `--timezone=${$app.timezone}`,
        `--country=${$app.country}`,
        '--newsletter=0',
      ]

```
 If I add `"country": "{{$global.env.PRESTASHOP_COUNTRY}}"` in prestashop-inputs.json, can work?

**Comment by andresbono** [comment]
@Nittarab, if you rebuild the container, it will work for the country but note that the flag `--language` is not there.

**Comment by Nittarab** [comment]
@andresbono i just realized it...
Yes I'm building my own container, do you think there is some workaround for the moment? I need to go in production quickly :sweat_smile:

**Comment by andresbono** [comment]
A workaround will be adding a modified `main.js` file in the Dockerfile that overwrites the existing one and build your own container.

You can hardcode your preferred language in the code. For instance, for country `Spain` and language `Spanish`:

```javascript
php.execute(
      'install/index_cli.php',
      [
        `--db_user=${databaseHandler.connection.user}`,
        `--db_password=${databaseHandler.connection.password}`,
        `--db_server=${databaseHandler.connection.host}:${databaseHandler.connection.port}`,
        `--db_name=${databaseHandler.connection.name}`,
        `--domain=${domains.httpDomain}`,
        `--firstname=${$app.firstName}`,
        `--lastname=${$app.lastName}`,
        `--password=${$app.password}`,
        `--email=${$app.email}`,
        `--timezone=${$app.timezone}`,
        '--country=es',
        '--language=es',
        '--newsletter=0',
      ]
```

We'll release the new version of the container soon as this changes should be simple. In the meantime, I hope this workaround helps you.

**Comment by Nittarab** [comment]
Thank you!
Is the bitnami prestashop package available on github? I have not found it
Will this feature be applied in previous versions of prestashop? I am currently using 1.7.4-4

**Comment by andresbono** [comment]
No I'm afraid that the package is not published on GitHub or any other code repository.

The feature will be included in the new versions of the container. Would be a problem for you to migrate to PrestaShop `1.7.5`?

**Comment by Nittarab** [comment]
No it should not be a problem, but at the moment we are not ready to do it.

I tryed to overwrite the `main.js` without success..

I tryed in 2 way:
`COPY main.js /opt/bitnami/prestashop/`
 end 
`COPY main.js /tmp/bitnami/pkg/install/prestashop-1.7.4-4-0-linux-amd64-debian-9/`

**Comment by andresbono** [comment]
Can you try copying it in the following location?

```
COPY main.js /root/.nami/components/com.bitnami/prestashop/
```

Let us know if it works!

**Comment by Nittarab** [comment]
Thank you so much @andresbono, it works!

**Comment by tompizmor** [comment]
We are glad to hear that worked! 

cc/ @andresbono

**Comment by andresbono** [comment]
@tompizmor, @Nittarab, reopening the issue.

**Comment by andresbono** [comment]
Hi again @Nittarab, we've just included this feature to our containers (latest version). Find the documentation here:

https://github.com/bitnami/bitnami-docker-prestashop#configuration

We also updated our Helm Chart: https://github.com/helm/charts/pull/10560.

Please let us know if you find any issues!
