### ISSUE TITLE
Access denied for user 'bn_prestashop'@'...' (using password: YES)

### ISSUE THREAD

**Issue by Tanoh-Hermann** [bitnami/bitnami-docker-prestashop#74]
**Description**
How to solve this problem? Access denied for user 'bn_prestashop'@'...' (using password: YES)
How to change 775 -> 777 in kubernetes?

**Steps to reproduce the issue:**

1. install stable/prestashop with helm image
2. set acces ALLOW_EMPTY_PASSWORD to no 

**Describe the results you received:**

<!- -->
Here is what logs show:
 mysql-c ERROR [canConnect] Connection with 'bn_prestashop' user is unsuccessful
Error executing 'postInstallation': Cannot connect to MySQL server:
MySQL command failed to run. Error: 
 ERROR 1045 (28000): Access denied for user 'bn_prestashop'@'...' (using password: YES)
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

-  using DigitalOcean Kubernetes on Debian do-kube-1.13.4

**Comment by marcosbc** [comment]
Hi @Tanoh-Hermann, if you set "ALLOW_EMPTY_PASSWORD" to "no", you also need to configure the MySQL/MariaDB database credentials (i.e. configure everything inside "externalDatabase" in the _values.yaml_ file).

**Comment by Tanoh-Hermann** [comment]
Thanks
