### ISSUE TITLE
Run console commands

### ISSUE THREAD

**Issue by orangevinz** [bitnami/bitnami-docker-prestashop#75]
Hi,

I's not an issue I guess but I can't access to the prestashop console via the container when I do :
`docker-compose run --rm prestashop /opt/bitnami/php/bin/php /opt/bitnami/prestashop/bin/console`

Is there any trick ton access to the php and then to the console ?

Thanks for your help

Vinz

**Comment by andresbono** [comment]
Hi @orangevinz, is there any error message that you are get when trying to access the console?

**Comment by orangevinz** [comment]
Hi @andresbono thanks for your help.

I get this message : 

`In ParameterBag.php line 102:
You have requested a non-existent parameter "secret".`

I think it's related to the parameters.yml file but the secret key exists in the config.yml so I can't figure how to access to the console... If you have a clue ;-)

Thanks

**Comment by andresbono** [comment]
Hi @orangevinz, it seems the problem is prestashop is not fully initialized when you run it with `docker-compose run --rm prestashop /opt/bitnami/php/bin/php /opt/bitnami/prestashop/bin/console`.

Can you try the following?

```
docker-compose up -d
docker-compose logs -f
# Wait until prestashop finishes the initialization, you will see "INFO  ==> Starting prestashop..."

docker-compose exec prestashop /opt/bitnami/prestashop/bin/console
```
