### ISSUE TITLE
Curl version doesn't support TLS 1.2 and PayPal payment module

### ISSUE THREAD

**Issue by rahardin** [bitnami/bitnami-docker-prestashop#76]
**Description**

Bitnami's Oracle Linux 7 based PrestaShop docker image provides curl version 7.29.0. This older curl version doesn't support TLS 1.2 which is required by PayPal in order to process PrestaShop payments. 

Thus, the Oracle Linux based PrestaShop image is not compatible with PayPal's official PrestaShop payment module provided by Braintree which is a PayPal subsidiary. 

Support of TLS v1.2 has been added with [curl version 7.34.0](https://curl.haxx.se/docs/manpage.html#--tlsv12).

The [documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) of the PayPal payment module says: "The Payment Card Industry (PCI) Council has mandated that early versions of TLS be retired from service. All organizations that handle credit card information are required to comply with this standard. As part of this obligation, Braintree & PayPal has upgraded its services to require TLS 1.2 for all HTTPS connections. Connections to the sandbox environment use only TLS 1.2. Check the version of your URL’s underlying security library. If you use OpenSSL libraries, please update them to at least version 1.0.1c." 

**Steps to reproduce the issue:**

1. Install PrestaShop payment module "[PayPal & Braintree official](op.com/en/payment-card-wallet/1748-paypal-braintree-official.html)"
2. Open the module's settings (in PrestaShop administration)
3. In module settings, click help -> check requirements

**Describe the results you received:**

The module will show message "Tls verification failed. TLS version is not compatible"

**Describe the results you expected:**

No error message. Compatibility with TLS 1.2 and the PayPal's PrestaShop payment module.

**Version**

- Bitnami PrestaShop Docker Image version

```
bitnami/prestashop:1.7.5-2-ol-7-r13
```

- Output of `docker version`:

```
18.09.6
```

**Comment by tompizmor** [comment]
Hello @rahardin,

Thanks for raising this issue. We will explore the options to update curl in the base image and come back to you once we have more information.

**Comment by beltran-rubo** [comment]
Hi @rahardin unfortunately we ship the latest version available for OL 7. Would be possible for you to use the Debian 9 version of the container that ships curl v7.52.1 ?

**Comment by rahardin** [comment]
Hi @beltran-rubo, Thanks for your response. Yes, I've switched to the Debian 9 version. The described issue does not occur with the Debian image. Perhaps you might like to publish an advice in README to temporarily use only the Debian variant until Oracle Linux is updated? It actually doesn't make much sense to use PrestaShop without TLS 1.2 support.

**Comment by alemorcuq** [comment]
Hi, @rahardin.

We've added a note to the README. Thank you for bringing this to our attention.

Regards,
Alejandro
