### ISSUE TITLE
The "Backups" directory located in the admin directory must be writable (CHMOD 755/777).

### ISSUE THREAD

**Issue by Nittarab** [bitnami/bitnami-docker-prestashop#78]
**Description**

**Steps to reproduce the issue:**

1. Run prestashop docker image, 
2. Access in to the admin panel
3. Do to Database> Backups > create new backups

**Describe the results you received:**
I get this error:

`The "Backups" directory located in the admin directory must be writable (CHMOD 755/777).`

**Additional information you deem important (e.g. issue happens only occasionally):**
I use the

**Version**
Helm chart `prestashop-6.6.3`
Prestashop version `1.7.5-2`
Docker image: `1.7.5-2-debian-9-r24`

I'm using GKE  `v1.13.6-gke.13`

I suppose this bug depends from the post-installation scripts that set the folder permission

**Comment by alemorcuq** [comment]
Hi, @Nittarab.

Thank you for reporting this. We will fix this and make a new release as soon as possible. In the meantime, you can change the owner of the `backups` directory to `daemon:daemon`:

```
chown -R daemon:daemon /opt/bitnami/prestashop/administration/backups
```

Regards,
Alejandro

**Comment by alemorcuq** [comment]
Hi, @Nittarab.

The issue should be fixed in these releases:

- `1.7.5-2-debian-9-r50`
- `1.7.5-2-ol-7-r57`

Thank you very much for reporting it. Please, don't hesitate to open a new issue if you find any problems.

Regards,
Alejandro
