### ISSUE TITLE
modifying basic configuration

### ISSUE THREAD

**Issue by ayxos** [bitnami/bitnami-docker-prestashop#80]
In order to upload a new theme I have to modify the php.ini file. 

1- Where is this file located?
2- What is the difference between the data in the docker volume and the data in the container? Where should I upload the new themes/modules/conf?
3- how to set up the docker-compose for production env with passwords?

**Comment by tompizmor** [comment]
>1- Where is this file located?

You can find it at `/opt/bitnami/php/etc/php.ini`

>2- What is the difference between the data in the docker volume and the data in the container? 

The data in the docker volume will be persisted between docker-container restarts, while any other data outside the persisted data dir (`/bitnami` inside the container) will be lost. In this container in particular, all PrestaShop application code is persisted.

> Where should I upload the new themes/modules/conf?

You can see the prestashop code at `/opt/bitnami/prestashop`

> 3- how to set up the docker-compose for production env with passwords?

Actually, docker-compose is not really the best choice to run containers in production. Instead, I would recommend you to take a look at our [Prestashop helm chart](https://github.com/helm/charts/tree/master/stable/prestashop)
