### ISSUE TITLE
Trouble scaling bitnami-docker-prestashop horizontally

### ISSUE THREAD

**Issue by Zir0-93** [bitnami/bitnami-docker-prestashop#82]
I would like to use horizontal scaling capabilities of a container orchestration platform like AWS ECS with this image (`bitnami/prestashop:1.7.6-4`). Is this supported? Is there any documentation on how to accomplish this?

My current setup consists of an ECS cluster of multiple containers running `bitnami/prestashop:1.7.6-4`  that mount the `/bitnami` directory to a shared EFS. They also all connect to a shared `mariadb` RDS Database in AWS. However, whenever  a new container is spun up, it seems to break all the other container's prestashop installation, and they all start returning the Apache2 Ubuntu Default Page, all except the most recently deployed container. I can replcate this behaviour locally as well by running multiple containers that all map `/bitnami` to a shared volume, and use a shared cloud database. 

Ideally, I would expect all the existing containers to work as normally when the cluster scales up. I figure I would need to edit the `Dockerfile` in some capacity to but I'm not sure where to start or know the easiest way to accomplish this, any advice would be appreciated, thanks!

**Comment by andresbono** [comment]
Hi @Zir0-93, we have never tested that configuration in the Prestashop container so we can't ensure the good behavior of it.

Can you share the logs of the containers in case there is some valuable information there?
