### ISSUE TITLE
Memory limit is always reset to 128M despite mounting php/conf directory

### ISSUE THREAD

**Issue by SzymonFortuna** [bitnami/bitnami-docker-prestashop#83]
**Description**

Does not matter what is the memory_limit in the /opt/bitnami/php/conf/php.ini, on container re-create, a memory_limit = 128M is added at the end of the file.

**Steps to reproduce the issue:**

1. edit mounted php.ini

**Describe the results you received:**

always memory_limit=128M is appended in the end of the file

**Describe the results you expected:**

not appending anything in php.ini file, ability to use custom php memory limit value

**Additional information you deem important (e.g. issue happens only occasionally):**

clearly a duplicate of this: https://github.com/bitnami/bitnami-docker-matomo/issues/36

**Version**

- Output of `docker version`:

```
Docker version 19.03.5, build 633a0ea
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 27
  Running: 2
  Paused: 0
  Stopped: 25
 Images: 183
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: P5CM:MUFQ:5AYW:I4GG:2KHN:E2TA:32SK:665Z:2LK7:HUQP:YQOW:6BBU
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 52
  Goroutines: 77
  System Time: 2020-04-04T18:49:50.4983982Z
  EventsListeners: 4
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.2, build 698e2846
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Docker for Mac

**Comment by juan131** [comment]
Hi @SzymonFortuna 

Thanks for reporting this issue! We have several issues complaining about being unable to customize the PHP memory limits other images. See https://github.com/bitnami/bitnami-docker-magento/issues/114 or https://github.com/bitnami/bitnami-docker-matomo/issues/36

We're working on including a new environment variable on every "PHP-based" image so you can properly customize it and it's not overwritten everytime you recreate the container. We'll keep you updated about our progress.

**Comment by miguelaeh** [comment]
Hi,
I would like to notify you that we just released a version that contains the env var `PHP_MEMORY_LIMIT` to allow you to modify the PHP memory limit.
You can find more information here: https://github.com/bitnami/bitnami-docker-prestashop/#php-configuration
Could you give it a try?

**Comment by SzymonFortuna** [comment]
@miguelaeh 
Hello, unfortunately it doesn't seem to work or I'm doing something wrong. BTW, Is the situtation analogous for upload max size and post size?
Thanks!

docker-compose.yml:
`
version: '2'

services:
  pma:
    image: 'phpmyadmin/phpmyadmin'
    environment:
      - MYSQL_USER=bn_prestashop
      - MYSQL_PASSWORD=bitnami_prestashop
    ports:
      - '8080:80'
    depends_on:
      - mariadb
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  prestashop:
    image: 'bitnami/prestashop:1.7'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
      - PHP_MEMORY_LIMIT=2048M
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - .:/bitnami
      - ./phpconf:/opt/bitnami/php/conf
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
`

/opt/bitnami/php/conf/php.ini (last 3 lines):
`
memory_limit = 2048M
memory_limit = 128M
upload_max_filesize = 25M`

**Comment by miguelaeh** [comment]
Hi @SzymonFortuna ,
We have tested it and we just saw that there is a regex that is not totally correct and because of that, it is adding your custom value at the end of the file instead of changing the the one that exists by default. In any case, as your custom value is added at the end of the file it will override the other one, so PHP should be using your custom value.
To check that your container is using the correct one you can execute this script:
```
<?php
$memory_limit = ini_get('memory_limit');
echo  $memory_limit;
```

**Comment by marcosbc** [comment]
Hi @SzymonFortuna, we've fixed this issue in a release with major changes to the Bitnami PrestaShop container image logic. Find out more here: [1.7.6-8-debian-10-r1](https://github.com/bitnami/bitnami-docker-prestashop#176-8-debian-10-r1). I'm proceeding to close this issue since it should be solved now.
