### ISSUE TITLE
Default configuration setup as Prestashop  Dev Docs say  

### ISSUE THREAD

**Issue by Nittarab** [bitnami/bitnami-docker-prestashop#84]
**Description**

Why the default php/apache/opcache/mysql configurations aren't set up as described in the developer docs: [https://devdocs.prestashop.com/1.7/scale/optimizations/](https://devdocs.prestashop.com/1.7/scale/optimizations/ )?

**Comment by andresbono** [comment]
Hi @Nittarab, thanks for opening this issue.

I understand that the link that you have shared is intended to optimize the performance of Prestashop but it states:

> Before making any change on your PrestaShop instance, it is highly recommended to perform some benchmarks.
>
> The idea behind this is to know what your baseline performance is, so that you can make sure that your changes are increasing your shop’s performance and not the other way around.

I understand from there that the optimal configuration might be different for different users. Applying all the suggestions from there might not have a beneficial effect in the end, it will depend on the particularities of each site.

Did you apply any of the steps to improve your own site?

**Comment by Nittarab** [comment]
I opened this issue because any time I use your container I have to modify the php.ini.
During the last year, the way to do that changed a lot. 

Have you really tried to use this container in production? 
Have you tried to have a product with 20 images and hundreds of combinations? 
Or maybe install a different theme? 
The default configuration of this container is just the minimum necessary to install Prestashop, if this is the goal of this repo, is ok. 

If you take a look in the prestashop/docker repo you can see their default configuration, for example:[https://github.com/PrestaShop/docker/blob/master/base/config_files/php.ini](https://github.com/PrestaShop/docker/blob/master/base/config_files/php.ini)

**Comment by andresbono** [comment]
Thanks for raising your concerns. Do you mind sharing the particular modifications that you do to the php.ini file?

With that information, in combination with documentation that you have shared, we will evaluate and review the default configuration that Prestashop should apply.

**Comment by Nittarab** [comment]
Thanks, @andresbono, sorry for my delay.
am I wrong or have you already made some change in the `docker.io/bitnami/prestashop:1.7.6-5-debian-10-r4`? 
first of all, I'll suggest you see this commit: [This configuration is not valid with Symfony](https://github.com/PrestaShop/docker/commit/8674e4db5f53d12ba5fdfa62aca0efbb5f83df43)
This causes a lots of error with the opcache, for example, when you install a new theme or try to delete the cache from the back-office. 

Other important configuration that normally  I have to apply:
```
max_input_vars = 20000
max_exevution_time = 300
memory_limit = 256M
```

I think this is the critical configurations

**Comment by andresbono** [comment]
Thanks for the suggestions, @Nittarab. We created an internal task to evaluate and improve the Prestashop configuration.

**Comment by Nittarab** [comment]
Thank you @andresbono. I think to already know this answer but I'll try. Are this change made in a some public repo?

**Comment by andresbono** [comment]
> Are this change made in a some public repo?

Unfortunately, no, @Nittarab. We are step by step migrating all our container configuration logic to GitHub, see https://github.com/bitnami/bitnami-docker-mariadb/tree/master/10.4/debian-10/rootfs/opt/bitnami/scripts for instance. For Prestashop, we are still not there.

In any case, both kind of containers are OSS.

**Comment by Nittarab** [comment]
Thank you, @andresbono this is good news.

**Comment by marcosbc** [comment]
Hi @Nittarab, we have finally made the change suggested by @andresbono. Read more on the update here: [1.7.6-8-debian-10-r1](https://github.com/bitnami/bitnami-docker-prestashop#176-8-debian-10-r1).

Unfortunately I cannot give an ETA for when we will implement the suggested optimizations, but feel welcome to send a PR implementing them, we'd be glad to review it!

**Comment by Nittarab** [comment]
Thank you @marcosbc  I'll work on it soon!

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-prestashop#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
