### ISSUE TITLE
How to install Let's encrypt

### ISSUE THREAD

**Issue by JavierGonzalezAlvarez** [bitnami/bitnami-docker-prestashop#90]
**Description**

I'd like to install Let's encrypt in bitnami-docker-prestashop and I just want to know who I can do it inside the container or where I should put the certs. It works fine but with an exception in security. Thanks

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:
lient: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```
(paste your output here)
```

- Output of `docker info`:
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.0-13-amd64
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.91GiB
 Name: vps815795
 ID: H5KC:5WFG:I4KB:7HZJ:AS4A:RV3Z:ZJ6U:RVIB:O6YO:BWON:PLQS:YFKI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
VPS

**Comment by javsalgar** [comment]
Hi,

From the README.md

> Users wanting to enable custom certificates are advised to mount their certificate files on top of the preconfigured ones at /certs.

Do you have the certificates or you need to create them? In our charts you can use solutions like cert-manager. I know that in docker-compose there's a certbot container, but I haven't tried it.

**Comment by JavierGonzalezAlvarez** [comment]
Hi,
Ok, I have ones. I'll overwrite my certs inside /certs
Thanks

**Comment by marcosbc** [comment]
Hi, since it looks like you've been able to solve your issue I've proceeded to close it. Feel free to add any comments if you think it's not the case.
