### ISSUE TITLE
Error PHP_MAX_INPUT_VARS

### ISSUE THREAD

**Issue by flavioski** [bitnami/bitnami-docker-prestashop#92]
Hello,
at this line

https://github.com/bitnami/bitnami-docker-prestashop/blob/df9a0a9da4b2187f03c1f21b473c77280aa89cf9/1.7/debian-10/rootfs/opt/bitnami/scripts/libphp.sh#L61

should be `max_input_vars` and not `max_input_time`

**Comment by carrodher** [comment]
Hi, thanks for reporting the issue, we just released a new Prestashop version (`1.7.6-8-debian-10-r19`), see 5db1bca522ebfb49e8d9c7bc6606c0af17d778ff. The issue should be solved using this new tag and all the associated rolling tags like `1.7`, `1.7.6-8`, `latest`, etc.

Please, feel free to reopen the issue if there is something that doesn't work as expected.
