### ISSUE TITLE
Enabling PHP-FPM 

### ISSUE THREAD

**Issue by ggfunnn** [bitnami/bitnami-docker-prestashop#94]
Hi guys. I don't know how to enable PHP-FPM in my container. I've already disabled mpm_prefork, php7_module and enabled mpm_event. After that php-fpm is running in the background (i can see it in the output of ps aux) but when i try to reach any of my sites, they are downloading PHP code instead of running it. I'm using Prestashop 1.7.6.8 with PHP 7.2.34

**Comment by juan131** [comment]
HI @ggfunnn 

As you mentioned, you need to edit the **/opt/bitnami/apache/conf/httpd.conf** configuration file:

```diff
- # LoadModule mpm_event_module modules/mod_mpm_event.so
+ LoadModule mpm_event_module modules/mod_mpm_event.so
- LoadModule mpm_prefork_module modules/mod_mpm_prefork.so
+ # LoadModule mpm_prefork_module modules/mod_mpm_prefork.so
- LoadModule php7_module modules/libphp7.so
+ # LoadModule php7_module modules/libphp7.so
```

Then, you need to reload Apache configuration, and start PHP-FPM in the background:

```console
$ apachectl -k graceful
$ php-fpm -F --pid /tmp/php-fpm.pid -y /opt/bitnami/php/etc/php-fpm.conf &
```

**Comment by ggfunnn** [comment]
I've run your commands but it still doesn't work. 

Here is output of ps aux:
`1001         1  0.5  0.0  14580 10124 ?        Ss   12:50   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND
1001        93  0.0  0.0 2309100 6300 ?        Sl   12:50   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND
1001        94  0.0  0.0 2309100 6300 ?        Sl   12:50   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND
1001        97  0.0  0.0 2309100 6300 ?        Sl   12:50   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND
1001       288  0.2  0.0   3868  3156 pts/0    Ss   12:50   0:00 /bin/bash
1001       293  1.2  0.0 1168444 43252 pts/0   S    12:50   0:00 php-fpm: master process (/opt/bitnami/php/etc/php-fpm.conf)
1001       294  0.0  0.0 1168444 8972 pts/0    S    12:50   0:00 php-fpm: pool www
1001       295  0.0  0.0 1168444 8972 pts/0    S    12:50   0:00 php-fpm: pool www
1001       296  0.0  0.0 1168444 8972 pts/0    S    12:50   0:00 php-fpm: pool www
1001       297  0.0  0.0 1168444 8972 pts/0    S    12:50   0:00 php-fpm: pool www
1001       298  0.0  0.0 1168444 8976 pts/0    S    12:50   0:00 php-fpm: pool www
1001       299  0.0  0.0 1168444 8976 pts/0    S    12:50   0:00 php-fpm: pool www
1001       300  0.0  0.0 1168444 8976 pts/0    S    12:50   0:00 php-fpm: pool www
1001       301  0.0  0.0 1168444 8980 pts/0    S    12:50   0:00 php-fpm: pool www
1001       302  0.0  0.0 1168444 8980 pts/0    S    12:50   0:00 php-fpm: pool www
1001       303  0.0  0.0 1168444 8980 pts/0    S    12:50   0:00 php-fpm: pool www
1001       304  0.0  0.0 1168444 8980 pts/0    S    12:50   0:00 php-fpm: pool www
1001       305  0.0  0.0 1168444 8984 pts/0    S    12:50   0:00 php-fpm: pool www
1001       306  0.0  0.0 1168444 8984 pts/0    S    12:50   0:00 php-fpm: pool www
1001       307  0.0  0.0 1168444 8984 pts/0    S    12:50   0:00 php-fpm: pool www
1001       308  0.0  0.0 1168444 8988 pts/0    S    12:50   0:00 php-fpm: pool www
1001       309  0.0  0.0 1168444 8988 pts/0    S    12:50   0:00 php-fpm: pool www
1001       310  0.0  0.0 1168444 8988 pts/0    S    12:50   0:00 php-fpm: pool www
1001       311  0.0  0.0 1168444 8992 pts/0    S    12:50   0:00 php-fpm: pool www
1001       312  0.0  0.0 1168444 8996 pts/0    S    12:50   0:00 php-fpm: pool www
1001       313  0.0  0.0 1168444 9000 pts/0    S    12:50   0:00 php-fpm: pool www
1001       314  0.0  0.0 1168444 8996 pts/0    S    12:50   0:00 php-fpm: pool www
1001       315  0.0  0.0 1168444 9000 pts/0    S    12:50   0:00 php-fpm: pool www
1001       316  0.0  0.0 1168444 9000 pts/0    S    12:50   0:00 php-fpm: pool www
1001       317  0.0  0.0 1168444 8664 pts/0    S    12:50   0:00 php-fpm: pool www
1001       318  0.0  0.0 1168444 9008 pts/0    S    12:50   0:00 php-fpm: pool www
1001       319  0.0  0.0 1168444 9004 pts/0    S    12:50   0:00 php-fpm: pool www
1001       320  0.0  0.0 1168444 9012 pts/0    S    12:50   0:00 php-fpm: pool www
1001       321  0.0  0.0 1168444 9004 pts/0    S    12:50   0:00 php-fpm: pool www
1001       322  0.0  0.0 1168444 9008 pts/0    S    12:50   0:00 php-fpm: pool www
1001       323  0.0  0.0 1168444 8620 pts/0    S    12:50   0:00 php-fpm: pool www
1001       324  0.0  0.0 1168444 9016 pts/0    S    12:50   0:00 php-fpm: pool www
1001       325  0.0  0.0 1168444 9012 pts/0    S    12:50   0:00 php-fpm: pool www
1001       326  0.0  0.0 1168444 9012 pts/0    S    12:50   0:00 php-fpm: pool www
1001       327  0.0  0.0 1168444 9016 pts/0    S    12:50   0:00 php-fpm: pool www
1001       328  0.0  0.0 1168444 9016 pts/0    S    12:50   0:00 php-fpm: pool www
1001       329  0.0  0.0 1168444 9020 pts/0    S    12:50   0:00 php-fpm: pool www
1001       330  0.0  0.0 1168444 9028 pts/0    S    12:50   0:00 php-fpm: pool www
1001       331  0.0  0.0 1168444 9020 pts/0    S    12:50   0:00 php-fpm: pool www
1001       332  0.0  0.0 1168444 9020 pts/0    S    12:50   0:00 php-fpm: pool www
1001       333  0.0  0.0 1168444 9024 pts/0    S    12:50   0:00 php-fpm: pool www
1001       334  0.0  0.0 1168444 9024 pts/0    S    12:50   0:00 php-fpm: pool www
1001       335  0.0  0.0 1168444 9028 pts/0    S    12:50   0:00 php-fpm: pool www
1001       336  0.0  0.0 1168444 9028 pts/0    S    12:50   0:00 php-fpm: pool www
1001       337  0.0  0.0 1168444 9028 pts/0    S    12:50   0:00 php-fpm: pool www
1001       338  0.0  0.0 1168444 9028 pts/0    S    12:50   0:00 php-fpm: pool www
1001       339  0.0  0.0 1168444 9036 pts/0    S    12:50   0:00 php-fpm: pool www
1001       340  0.0  0.0 1168444 9036 pts/0    S    12:50   0:00 php-fpm: pool www
1001       341  0.0  0.0 1168444 9036 pts/0    S    12:50   0:00 php-fpm: pool www
1001       342  0.0  0.0 1168444 9032 pts/0    S    12:50   0:00 php-fpm: pool www
1001       343  0.0  0.0 1168444 9040 pts/0    S    12:50   0:00 php-fpm: pool www
1001       344  0.0  0.0 1168444 9040 pts/0    S    12:50   0:00 php-fpm: pool www
1001       345  0.0  0.0 1168444 9036 pts/0    S    12:50   0:00 php-fpm: pool www
1001       346  0.0  0.0 1168444 9040 pts/0    S    12:50   0:00 php-fpm: pool www
1001       347  0.0  0.0 1168444 9040 pts/0    S    12:50   0:00 php-fpm: pool www
1001       348  0.0  0.0 1168444 8980 pts/0    S    12:50   0:00 php-fpm: pool www
1001       349  0.0  0.0 1168444 8980 pts/0    S    12:50   0:00 php-fpm: pool www
1001       350  0.0  0.0 1168444 8980 pts/0    S    12:50   0:00 php-fpm: pool www
1001       351  0.0  0.0 1168444 8980 pts/0    S    12:50   0:00 php-fpm: pool www
1001       352  0.0  0.0 1168444 8980 pts/0    S    12:50   0:00 php-fpm: pool www
1001       353  0.0  0.0 1168444 8980 pts/0    S    12:50   0:00 php-fpm: pool www
1001       354  0.0  0.0 1168444 8980 pts/0    S    12:50   0:00 php-fpm: pool www
1001       355  0.0  0.0 1168444 8980 pts/0    S    12:50   0:00 php-fpm: pool www
1001       356  0.0  0.0 1168444 8980 pts/0    S    12:50   0:00 php-fpm: pool www
1001       357  0.0  0.0 1168444 8980 pts/0    S    12:50   0:00 php-fpm: pool www
1001       358  0.0  0.0 1168444 8980 pts/0    S    12:50   0:00 php-fpm: pool www
1001       359  0.0  0.0 1168444 8984 pts/0    S    12:50   0:00 php-fpm: pool www
1001       360  0.0  0.0 1168444 8984 pts/0    S    12:50   0:00 php-fpm: pool www
1001       361  0.0  0.0 1168444 8984 pts/0    S    12:50   0:00 php-fpm: pool www
1001       362  0.0  0.0 1168444 8984 pts/0    S    12:50   0:00 php-fpm: pool www
1001       363  0.0  0.0 1168444 8984 pts/0    S    12:50   0:00 php-fpm: pool www
1001       364  0.0  0.0 1168444 8984 pts/0    S    12:50   0:00 php-fpm: pool www
1001       365  0.0  0.0 1168444 8984 pts/0    S    12:50   0:00 php-fpm: pool www
1001       366  0.0  0.0 1168444 8984 pts/0    S    12:50   0:00 php-fpm: pool www
1001       367  0.0  0.0 1168444 8984 pts/0    S    12:50   0:00 php-fpm: pool www
1001       368  0.0  0.0 1168444 8984 pts/0    S    12:50   0:00 php-fpm: pool www
1001       369  0.0  0.0   7640  2760 pts/0    R+   12:50   0:00 ps aux`

And here is file that is dowloaded when i try to reach my site:
`<?php
/**
 * 2007-2019 PrestaShop and Contributors
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/OSL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future. If you wish to customize PrestaShop for your
 * needs please refer to https://www.prestashop.com for more information.
 *
 * @author    PrestaShop SA <contact@prestashop.com>
 * @copyright 2007-2019 PrestaShop SA and Contributors
 * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 * International Registered Trademark & Property of PrestaShop SA
 */

require dirname(__FILE__).'/config/config.inc.php';
Dispatcher::getInstance()->dispatch();`

**Comment by juan131** [comment]
Hi @ggfunnn 

I am afraid you require more modifications (apart from the ones mentioned earlier).. Sorry:

-  Modify **/opt/bitnami/apache/conf/httpd.conf** configuration file like this:

```diff
-#LoadModule actions_module modules/mod_actions.so
+LoadModule actions_module modules/mod_actions.so
...
-AddType application/x-httpd-php .php
+<IfModule !php7_module>
+  AddType application/x-httpd-php .php
+  Action application/x-httpd-php "/bitnami-error-php-fpm-did-not-handle-the-connection"
+  Define USE_PHP_FPM
+  Include "/opt/bitnami/apache/conf/bitnami/php-fpm.conf"
+</IfModule>
```

- Create the **/opt/bitnami/apache/conf/bitnami/php-fpm.conf** file wit this content:

```
DirectoryIndex index.html index.htm index.php
<IfDefine USE_PHP_FPM>
  <Proxy "unix:/opt/bitnami/php/var/run/www.sock|fcgi://www-fpm" timeout=300>
  </Proxy>
  <FilesMatch \.php$>
    <If "-f %{REQUEST_FILENAME}">
      SetHandler "proxy:fcgi://www-fpm"
    </If>
  </FilesMatch>
</IfDefine>
```

- Create the **/opt/bitnami/php/etc/php-fpm.d/www.conf** file wit this content:

```console
[www]
include=/opt/bitnami/php/etc/environment.conf
include=/opt/bitnami/php/etc/common.conf
pm=dynamic
listen=/opt/bitnami/php/var/run/www.sock
listen.allowed_clients=127.0.0.1
pm.max_children=30
pm.start_servers=20
pm.min_spare_servers=20
pm.max_spare_servers=22
pm.max_requests=5000
```

Finally, reload Apache configuration and start PHP-FPM:

```
$ apachectl -k graceful
$ php-fpm -F --pid /tmp/php-fpm.pid -y /opt/bitnami/php/etc/php-fpm.conf &
```

**Comment by ggfunnn** [comment]
Thanks! It works now.
