### ISSUE TITLE
Xdebug installation the simplest way.

### ISSUE THREAD

**Issue by adrienpsl** [bitnami/bitnami-docker-prestashop#96]
Hello, 

What is the best way to install Xdebug on this container ?

https://xdebug.org

Thanks ! :).

**Comment by marcosbc** [comment]
Hi @adrienpsl, XDebug is already installed but not enabled by default. See "/opt/bitnami/php/etc/php.ini":

```
;[XDebug]
;zend_extension = xdebug
;xdebug.remote_enable = true
;xdebug.remote_host = 127.0.0.1
;xdebug.remote_port = 9000
;xdebug.remote_handler = dbgp
;xdebug.profiler_enable = 1
;xdebug.profiler_output_dir = /tmp
```

To enable it, you would need to uncomment those lines.

Hope it helps!

**Comment by adrienpsl** [comment]
Ho thank you !  :).
