### ISSUE TITLE
Install Prestashop in IBM Cloud

### ISSUE THREAD

**Issue by datta-TG** [bitnami/bitnami-docker-prestashop#99]
PrestaShop is a free and open source content management system, designed to build e-commerce online stores from scratch. This documentation will guide you on how to install Prestashop on the IBM Cloud using the Kubernetes Service. Simple and effective.

## Pre-requisites

You must have an account created in IBM Cloud. The account needs to either be *Pay-As-You-Go* or *Subscription*. Click [here](https://cloud.ibm.com/docs/account?topic=account-accounts "here") to read more.
If you have a Lite account, you can upgrade it. Click [here](https://cloud.ibm.com/docs/account?topic=account-account-getting-started#account-gs-upgrade "here") to learn how to upgrade.

## Step 1: Provision Kubernetes Cluster

* Click on the search section at the top of the main page, type Kubernetes, and then choose Kubernetes Service.

![Kubernetes1](https://user-images.githubusercontent.com/70336951/105729101-dd25a980-5efa-11eb-9a69-c8b1dc76b492.png)

* In the new window, select between the free and standard type under "Pricing plan". Once selected, click on create.

![KubernetesPaid1](https://user-images.githubusercontent.com/70336951/105729118-e151c700-5efa-11eb-82c4-018f18381d71.PNG)

We'll choose the Standard Plan for this documentation as the Free Plan may fall short of resources when deploying your pods. We highly recommend using a Standard Plan with the hardware that suits you the best. If you're selecting the Standard Plan, please make sure you select the adequate requirements,

* Select your Kubernetes Version to be the latest available or the required one by your application. In this example, we have set it to be '1.18.13'.
* Select Infrastructure as 'Classic'.
* Leave Resource Group to 'Default'.
* Select Geography to the one that suits you better or that fits your infrastructure.
* Select Availability to be 'Single Zone' or 'Multi Zone' depending on your needs.
* Select a Worker Zone that suits you better or that fits your infrastructure.

![KubernetesPaid2](https://user-images.githubusercontent.com/70336951/105729181-f4fd2d80-5efa-11eb-8b34-876d0c07ff20.PNG)

* Select the number of workers in Worker Pool.
* Give your Worker Pool a name.
* Leave the Encrypt Local Disk option 'On'
* Choose 'Both private and public endpoints' on Master Service Endpoint

![KubernetesPaid4](https://user-images.githubusercontent.com/70336951/105729158-ed3d8900-5efa-11eb-8548-19361ce1720f.PNG)

* Give your cluster a name in 'cluster-name'
* Provide the tags to your cluster and click on Create.

![KubernetesPaid5](https://user-images.githubusercontent.com/70336951/105729236-01818600-5efb-11eb-8050-e777662fbdfb.PNG)

Wait a few minutes while your cluster is deployed.

![KubernetesPaid3](https://user-images.githubusercontent.com/70336951/105729262-080ffd80-5efb-11eb-8744-fca009a36042.PNG)

The following checkmark and the word 'normal' will appear once the Kubernetes Cluster is deployed. You can check it under your cluster section which is located in your *Resources List*.

![KubernetesPaid6](https://user-images.githubusercontent.com/70336951/105729294-0fcfa200-5efb-11eb-9639-eef85e6e321f.PNG)

## Step 2:  Deploy IBM Cloud Block Storage plug-in

* Click on the search section at the top of the main page, select IBM Cloud Block Storage, and click on it.

![StoragePaid1](https://user-images.githubusercontent.com/70336951/105729327-18c07380-5efb-11eb-8681-f07957ae09b1.PNG)

* A new window opens, select the cluster and enter the name you want for this workspace, in this case, it will be called _storage-example_, accept the terms, click *Install* and wait a few minutes.

![StoragePaid2](https://user-images.githubusercontent.com/70336951/105729350-1e1dbe00-5efb-11eb-9861-3a37b28d5b40.PNG)

## Step 3: Install Prestashop

* Click on the search section at the top of the main page, type Prestashop, and click on it.

![Presta1](https://user-images.githubusercontent.com/70336951/105729435-35f54200-5efb-11eb-9805-4b3b6ea7f069.PNG)

* A new window opens, select the cluster and enter the name you want for the Prestashop workspace; in this case, it will be called _prestashop-example_; then, go to the bottom to find the workspace parameters.

You can modify the different installation parameters at the bottom. We will leave them by default except for the credentials Prestashop uses for its database and its application. You will need the first to access your database console and the second one to access your new Prestashop application. You can read more about setting up the parameters [here](https://cloud.ibm.com/catalog/content/prestashop "here").

Make sure you set up correctly the email and password for the application in the _prestashopEmail_ and _prestashopPassword_ variables. 

![Presta6](https://user-images.githubusercontent.com/70336951/105729451-3beb2300-5efb-11eb-9df1-ee660f3e0384.PNG)

![Presta7](https://user-images.githubusercontent.com/70336951/105729466-40174080-5efb-11eb-837d-06c8a04a3187.PNG)

You can also set up a new database user in the  _mariadb.auth.username_ variable. Don't forget to set the password for that user in the _mariadb.auth.password_ variable. The admin user will be _root_ by default, and you can change its password in the _mariadb.auth.rootPassword_.

![Presta4](https://user-images.githubusercontent.com/70336951/105729477-44435e00-5efb-11eb-995d-1a5d44efae33.PNG)

![Presta5](https://user-images.githubusercontent.com/70336951/105729488-47d6e500-5efb-11eb-9df1-35771766f32f.PNG)

![Presta3](https://user-images.githubusercontent.com/70336951/105729505-4b6a6c00-5efb-11eb-8de8-e8004717a17f.PNG)

When you're done, accept the terms, and click on *Install*.

![Presta2](https://user-images.githubusercontent.com/70336951/105729517-50c7b680-5efb-11eb-8a73-c86014abd956.PNG)

## Step 4: Verify Installation

* Go to *Resources List* in the Left Navigation Menu and click on *Kubernetes*.

![test1](https://user-images.githubusercontent.com/70336951/105729631-705edf00-5efb-11eb-8a09-74cfd34efc64.png)

* Click the *Actions* button and select *Web terminal*.

![test2](https://user-images.githubusercontent.com/70336951/105729641-72c13900-5efb-11eb-8344-9f016dad0fc2.PNG)

* A window opens to install the web terminal, click on install and wait a few minutes. The window will pop up at the buttom If the web terminal is already installed.

![test3](https://user-images.githubusercontent.com/70336951/105729680-794fb080-5efb-11eb-8ad5-2dbe2d233d6a.PNG)

![test7](https://user-images.githubusercontent.com/70336951/105729703-7ce33780-5efb-11eb-9203-1bc4ce34cb52.PNG)

* Once you have installed the terminal, open it and type the following command. It will show you the workspaces of your cluster. You can see *prestashop-example* is now active.

`$ kubectl get ns`

![testpresta1](https://user-images.githubusercontent.com/70336951/105729718-810f5500-5efb-11eb-8101-41de7db5fe0f.PNG)

* You can then obtain more data about the service and it's pods.

`$ kubectl get pod -n NAMESERVICE -o wide`

![testpresta2](https://user-images.githubusercontent.com/70336951/105729737-853b7280-5efb-11eb-8828-ccd05cbc932a.PNG)

* Find the public IP the load balacer pod is using, you will need it to access your Prestashop application.

`$ kubectl get service -n NAME SERVICE`

![testpresta3](https://user-images.githubusercontent.com/70336951/105729750-89679000-5efb-11eb-99a4-74ac63f0b77d.PNG)

* You can also select the mariadb pod within your service using bash so you can start and use the database console.

`$ kubectl exec --stdin --tty PODNAME -n NAMESPACE -- /bin/bash`

![testpresta5](https://user-images.githubusercontent.com/70336951/105729767-8ff60780-5efb-11eb-8749-f00df2b18ece.PNG)

* Once you're inside the pod terminal, you can execute the following command to login into mariadb and create and manage your databases. Use your previously created password.

`$ mysql -u root -p`

![testpresta4](https://user-images.githubusercontent.com/70336951/105729797-95535200-5efb-11eb-8b42-e7c3a6497b7b.PNG)

You have finished the installation and enjoy your new Prestashop site by accessing the load balancer's public IP. It is important to note that the VPC selected in the Kubernetes Cluster created should have an Internet Gateway to correctly access the IP. You can also assign a custom domain by modifying the corresponding variable in the Prestashop installation parameters.

**Comment by carrodher** [comment]
Thanks for the info. As it seems that there is no issue we should take action and everything works properly, I am going to mark this issue as “Closed” so it can be used by other users looking for information as if it were documentation
